server:
  port: 8080
  
  app:
  stun:
    urls: "stun:stun.l.google.com:19302"
  turn:
    urls: "turn:your-turn-server.com:3478"
    username: "your-turn-server-username"
    password: "your-turn-server-password"
